### ISSUE TITLE
0x52 - WIchiFarm#pendingRewards suffers from significant precision loss causing loss of rewards

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-blueberry-judging#137]
0x52

high

# WIchiFarm#pendingRewards suffers from significant precision loss causing loss of rewards

## Summary

IchI LPs are 18 dp tokens while IchiPerShare is only 9 dp. In conjunction with how small typical Ichi LP values are, the precision loss caused during calculation can cause nontrivial loss to users. 

## Vulnerability Detail

[WIchiFarm.sol#L122-L127](https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/wrapper/WIchiFarm.sol#L122-L127)

        (uint256 enIchiPerShare, , ) = ichiFarm.poolInfo(pid);
        uint256 stIchi = (stIchiPerShare * amount).divCeil(10 ** lpDecimals);
        uint256 enIchi = (enIchiPerShare * amount) / (10 ** lpDecimals); <- @audit-issue precision loss here
        uint256 ichiRewards = enIchi > stIchi ? enIchi - stIchi : 0;
        // Convert rewards to ICHI(v2) => ICHI v1 decimal: 9, ICHI v2 Decimal: 18
        ichiRewards *= 1e9;

Since stIchi and enIchi are calculated separate from eachother, it results in precision loss. Normally this precision loss would result in trivial losses but in these circumstances the losses could be quite large. This is because IchiPerShare is stored as a 9 dp value. Additionally even large deposits result in [very low LP values](https://etherscan.io/tx/0xe6acb00276123aae88698476e724b59e61f16ce3b7ffac23bdbedf4578a0b23d). This creates a scenario where users can lose substantial rewards to precision loss.

Example:
A user deposits $500 worth of ICHI to get ICHI LP. This deposit results in the user receiving ~860000000 LP (based on current conditions). Now imagine a the IchiPerShare increases by 1e9 (1 unit of IchIV1). Based on the current math this would result in the user getting 0 in rewards:

860000000 * 1e9 / 1e18 = 0.86 which is truncated to 0.

## Impact

Precision loss will cause permanent loss to the user

## Code Snippet

[WIchiFarm.sol#L110-L133](https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/wrapper/WIchiFarm.sol#L110-L133)

## Tool used

Manual Review

## Recommendation

Calculate rewards like [WConvexPools](https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/wrapper/WConvexPools.sol#L110-L121) to reduce precision loss as much as possible.

**Comment by bwafflef** [comment]
@sherlock-admin @Gornutz 
I think the logic of `pendingRewards` function in `WIchiFarm.sol` contract is accurate and there is no loss of rewards.
For this, we need to have a look at `accShare` logic of `IchiFarm` contract. `accShare` is the variable represents `rewards per input amount(lp)`. Reward token of `IchiFarm` contract is `ICHI(v1)` token which it's decimal is 9, so both of `stIchi` and `enIchi` has 9 decimals (the same as `ICHI(v1)` token). This `ICHI(v1)` token is converted to `ICHI(v2)` token  which has 18 decimals, and distributed to users in `burn` function (https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/wrapper/WIchiFarm.sol#L177-L180)

For this case ( `860000000 * 1e9 / 1e18 = 0.86 which is truncated to 0` ), reward is calculated as 0 not only on our side but also `IchiFarm` contract side and it's not a problem at all.

**Comment by IAm0x52** [comment]
Your comment would be true if a single user made up the entire pool. However the pool is an aggregate of many users that all earn rewards as a whole (all LP deposited to the same address). It would be true that each user may not accumulate more than the minimum individually but as a collective they would exceed it and therefore should be due their fair share.

**Comment by bwafflef** [comment]
> Your comment would be true if a single user made up the entire pool. However the pool is an aggregate of many users that all earn rewards as a whole (all LP deposited to the same address). It would be true that each user may not accumulate more than the minimum individually but as a collective they would exceed it and therefore should be due their fair share.

It seems like your suggestion might be correct, but it will never happen that `as a collective they would exceed it and therefore should be due fair share`.

**Comment by IAm0x52** [comment]
If there are two users and they deposit 500000000 LP each. Each user will be due:

`500000000 * 1e9 / 1e18 = 0.5 => 0`

Together there will be 1000000000 LP so as a whole they will earn from the ICHI farm:

`1000000000 * 1e9 / 1e18 = 1`

If each user were to deposit independently, neither would receive a reward form the farm (both truncate to 0) but when put in together they earn 1 which isn't truncated. Therefore in that case both users should be due their fair share

**Comment by bwafflef** [comment]
@IAm0x52  i get your point, but reward loss in this case is 0.5 wei, which is quite small. I'm not sure about the solution to handle this kind of minor amount smaller than 1 wei. Do you have any suggestion?

**Comment by bwafflef** [comment]
Also the important point we need to consider here is that reward calc logic in `pendingRewards` function is the same in `IchiFarm` contract following masterChef contract logic. This means there is a loss of 0.5 wei ICHI(reward) when we claim ICHI reward from `IchiFarm` contract.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
As mentioned by sponsor, the impact of this issue does not reach H. It's valid M.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> As mentioned by sponsor, the impact of this issue does not reach H. It's valid M.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Based on the comment above, this issue can be a valid medium

**Comment by hrishibhat** [comment]
Escalation accepted

Valid low 
After further discussions and review of the comments, the impact of the issue is not significant enough for a valid medium. 
The losses here are of the order 9.9e8 loss out of a 18 dp token.

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
>
>Valid low 
>After further discussions and review of the comments, the impact of the issue is not significant enough for a valid medium. 
>The losses here are of the order 9.9e8 loss out of a 18 dp token. 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
