### ISSUE TITLE
n1punp - Transaction will revert when using USDT tokens (or other non-compliant ERC20 tokens)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-blueberry-judging#15]
n1punp

high

# Transaction will revert when using USDT tokens (or other non-compliant ERC20 tokens)

## Summary
Transaction will revert when using USDT tokens

## Vulnerability Detail
USDT token has a non-standard `approve` function implementation, as it doesn't return a boolean. So, normal `IERC20` interface will cause the EVM to expect a boolean as a return value but it won't get any when `token` is USDT, and so the tx will revert. 

## Impact
Any contract functionality that utilizes `_ensureApprove` will cause tx revert when the token is USDT, including `lend`, `withdrawLend` , and executions in all spells.

## Code Snippet
https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/utils/EnsureApprove.sol#L22-L23

## Tool used

Manual Review

## Recommendation
- use `safeApprove` from OpenZeppelin's standard `SafeERC20.sol`

**Comment by Gornutz** [comment]
USDT only can call approve function when the allowance is zero or to set the allowance to zero first.
