### ISSUE TITLE
nobody2018 - CurveSpell#openPositionFarm will always revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-blueberry-judging#51]
nobody2018

high

# CurveSpell#openPositionFarm will always revert

## Summary

Before calling `ICurvePool#add_liquidity` to deposit tokens, each token needs to be approved to the pool. If the approved amount is different from the parameters passed into `ICurvePool#add_liquidity`, it will cause `erc20.transferFrom` revert inside the function. In this way, `openPositionFarm` will also revert.

## Vulnerability Detail

**The root of this problem is that `openPositionFarm` uses the return value of `ERC20.balanceOf(address(this)` as the parameter of  `ICurvePool#add_liquidity`**. For simplicity, assume that CurveSpell supports an lptoken which contains two tokens : A and B.

**Bob transferred 1wei of A and B to the CurveSpell contract**. Alice opens a position by calling `BlueBerryBank#execute`, and the flow is as follows:

1.  enter `CurveSpell#openPositionFarm`.
2.  call `_doLend` to deposit isolated collaterals.
3.  call `_doBorrow` to borrow 100e18 A token.
4.  `A.approve(pool, 100e18)`.
5.  `suppliedAmts[0] = A.balance(address(this)) = 100e18+1wei`, `suppliedAmts[1] = B.balance(address(this)) = 1wei`.
6.  call `ICurvePool(pool).add_liquidity(suppliedAmts, minLPMint)`, then revert because the approved amount is not enough.

Therefore, no one can successfully open a position.

## Impact

`CurveSpell#openPositionFarm` will always revert. It cannot be restored manually.

## Code Snippet

https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/spell/CurveSpell.sol#L90-L115

## Tool used

Manual Review

## Recommendation

```diff
--- a/blueberry-core/contracts/spell/CurveSpell.sol
+++ b/blueberry-core/contracts/spell/CurveSpell.sol
@@ -91,25 +91,28 @@ contract CurveSpell is BasicSpell {
         if (tokens.length == 2) {
             uint256[2] memory suppliedAmts;
             for (uint256 i = 0; i < 2; i++) {
-                suppliedAmts[i] = IERC20Upgradeable(tokens[i]).balanceOf(
-                    address(this)
-                );
+                if (tokens[i] == param.borrowToken) {
+                    suppliedAmts[i] = borrowBalance;
+                    break;
+                }
             }
             ICurvePool(pool).add_liquidity(suppliedAmts, minLPMint);
         } else if (tokens.length == 3) {
             uint256[3] memory suppliedAmts;
             for (uint256 i = 0; i < 3; i++) {
-                suppliedAmts[i] = IERC20Upgradeable(tokens[i]).balanceOf(
-                    address(this)
-                );
+                if (tokens[i] == param.borrowToken) {
+                    suppliedAmts[i] = borrowBalance;
+                    break;
+                }
             }
             ICurvePool(pool).add_liquidity(suppliedAmts, minLPMint);
         } else if (tokens.length == 4) {
             uint256[4] memory suppliedAmts;
             for (uint256 i = 0; i < 4; i++) {
-                suppliedAmts[i] = IERC20Upgradeable(tokens[i]).balanceOf(
-                    address(this)
-                );
+                if (tokens[i] == param.borrowToken) {
+                    suppliedAmts[i] = borrowBalance;
+                    break;
+                }
             }
             ICurvePool(pool).add_liquidity(suppliedAmts, minLPMint);
         }
```

Duplicate of #47

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This issuse is valid M. The root of this problem is that openPositionFarm uses the return value of ERC20.balanceOf(address(this) as the parameter of  ICurvePool#add_liquidity. The Summary of this report has described the cause of the problem.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> This issuse is valid M. The root of this problem is that openPositionFarm uses the return value of ERC20.balanceOf(address(this) as the parameter of  ICurvePool#add_liquidity. The Summary of this report has described the cause of the problem.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Senior watson's comment:

this is a duplicate of https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/47

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #47

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #47 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
