### ISSUE TITLE
nobody2018 - By AuraSpell#closePositionFarm, a user can take token0 or token1 left by another user when closing a position

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-blueberry-judging#54]
nobody2018

high

# By AuraSpell#closePositionFarm, a user can take token0 or token1 left by another user when closing a position

## Summary

`AuraSpell#closePositionFarm` removes liquidity by calling `IBalancerVault.ExitPoolRequest`. The way it is called will receive token0 and token1. For simplicity, assume borrowToken is token0. When `_doRepay` is called, token0 in the contract is used for repayment, but token1 in the contract is not processed and stuck in the AuraSpell contract. An attacker can steal token1 via `AuraSpell#closePositionFarm`.

## Vulnerability Detail

We assume a scenario to describe this problem. Suppose alice's `borrowToken` is token0. Alice triggers `AuraSpell.closePositionFarm` by calling `BlueBerryBank.execute`. Let's take a look at the code snippet of `AuraSpell#closePositionFarm`:

```solidity
// 3. Remove liquidity
            (address[] memory tokens, , ) = wAuraPools.getPoolTokens(lpToken);
            uint[] memory minAmountsOut = new uint[](2);
            wAuraPools.getVault(lpToken).exitPool(
                IBalancerPool(lpToken).getPoolId(),
                address(this),
                address(this),
->              IBalancerVault.ExitPoolRequest(tokens, minAmountsOut, "", false)
            );
```

By the assignment of the `ExitPoolRequest` structure in the above code, the AuraSpell contract will receive token0 and token1. token0 is used to repay the debt of alice's position, and token1 is stuck in the AuraSpell contract. Alice's transaction executes successfully.

Now, bob notices that there is some token1 stuck in the contract. So, **he opened a small new position, borrowToken is token1**. After that, he closes the position by `AuraSpell.closePositionFarm`, so that he can take away all the token1 stuck in the contract. **The reason is** that at the end of `AuraSpell.closePositionFarm`, `_doRefund(param.borrowToken)` will be called to transfer all borrowTokens in the contract to the owner of the position.

## Impact

The attacker can take away all token0 and token1 that all users left in the contract when closing the position.

## Code Snippet

https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/spell/AuraSpell.sol#L182-L189

## Tool used

Manual Review

## Recommendation

`IBalancerVault#exitPool` supports withdrawing a single token as long as `ExitPoolRequest.userData` is correctly encoded as following:

- Single Asset Exit
    - userData ABI
        - `['uint256', 'uint256', 'uint256']`
    - userData
        - `[EXACT_BPT_IN_FOR_ONE_TOKEN_OUT, bptAmountIn, exitTokenIndex]`

For details, please refer to [[pool-exits](https://docs.balancer.fi/reference/joins-and-exits/pool-exits.html)](https://docs.balancer.fi/reference/joins-and-exits/pool-exits.html).

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is a valid M/H. The reason is similar to what I gave in #55. They are issues that occur together and have different effects.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> This is a valid M/H. The reason is similar to what I gave in #55. They are issues that occur together and have different effects.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Senior watson's comments:

Very interesting escalation. The submission is wrong because it would revert rather than leaving any tokens in the contract but their recommendation to fix the exit data is correct. Should either be dupe of #129 or invalid imo

Judge comment:

it is ok to leave it a duplicate of https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/129

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
Given that the underlying issue is described incorrectly as there are no tokens left in the contract because of incorrect userdata since it would revert. 
Having correct recommendations, although appreciated, is not sufficient to make a submission valid. 

Tagging @Gornutz so inform them of the recommendation in this issue.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Invalid issue
> Given that the underlying issue is described incorrectly as there are no tokens left in the contract because of incorrect userdata since it would revert. 
> Having correct recommendations, although appreciated, is not a sufficient to make a submissions valid. 
> 
> Tagging @Gornutz so inform them of the recommendation in this issue. 
> 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
