### ISSUE TITLE
nobody2018 - Attacker can front-run AuraSpell#openPositionFarm to take away user's borrowToken

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-blueberry-judging#55]
nobody2018

high

# Attacker can front-run AuraSpell#openPositionFarm to take away user's borrowToken

## Summary

The flow of `AuraSpell#openPositionFarm` has 7 steps. The 3th step is to add liquidity on Balancer to get lptoken. The implementation of this step cannot get any lptoken due to not calling `IBalancerVault.JoinPoolRequest`. So borrowToken is stuck in contract. In this way, the second parameter passed to `wAuraPools.mint` in the 7th step will be 0, resulting in revert. **However, if an attacker monitors   `AuraSpell#openPositionFarm` and finds it profitable, he can front-run it and transfer a certain amount of lptoken to AruaSpell**. So the transaction will not revert.

## Vulnerability Detail

Assume that **lpToken contains token0 and token1**. Alice's `borrowToken` is token0. Alice triggers `AuraSpell.openPositionFarm` by calling `BlueBerryBank.execute`. Bob monitors this tx and finds it is profitable, so he front-runs it. **The flow after being front-run by bob** is as follows:

1.  bob calls lptoken.transfer(address(AuraSpell), 10e18). Then **`lptoken.balanceOf(address(AuraSpell)) = 10e18`**. The following steps are alice's tx flow.
    
2.  call `_doLend` to deposit isolated collaterals.
    
3.  call `_doBorrow` to borrow 50e18 token0.
    
4.  `maxAmountsIn[0] = IERC20(tokens[0]).balanceOf(address(this)) = 50e18`.
    `maxAmountsIn[1] = IERC20(tokens[1]).balanceOf(address(this)) = 0`.
    `poolAmountFromA = (maxAmountsIn[0] * totalLPSupply) / balances[0]`, poolAmountFromA > 0.
    `poolAmountFromB = (maxAmountsIn[1] * totalLPSupply) / balances[1] = 0`.
    `poolAmountOut = poolAmountFromA > poolAmountFromB ? poolAmountFromB: poolAmountFromA = 0`.
    This makes `if (poolAmountOut > 0)` statement will not be met. `vault.joinPool` will be skipped. So this step will not get any lptoken. **50e18 token0 is stuck in contract**.
    
    ```solidity
    ......
                IBalancerVault vault = wAuraPools.getVault(lpToken);
                _ensureApprove(param.borrowToken, address(vault), borrowBalance);
    
                (address[] memory tokens, uint256[] memory balances, ) = wAuraPools
                    .getPoolTokens(lpToken);
                uint[] memory maxAmountsIn = new uint[](2);
    ->          maxAmountsIn[0] = IERC20(tokens[0]).balanceOf(address(this));
    ->          maxAmountsIn[1] = IERC20(tokens[1]).balanceOf(address(this));
    
                uint totalLPSupply = IBalancerPool(lpToken).totalSupply();
                // compute in reverse order of how Balancer's `joinPool` computes tokenAmountIn
    ->          uint poolAmountFromA = (maxAmountsIn[0] * totalLPSupply) /
                    balances[0];
    ->          uint poolAmountFromB = (maxAmountsIn[1] * totalLPSupply) /
                    balances[1];
    ->          uint poolAmountOut = poolAmountFromA > poolAmountFromB
                    ? poolAmountFromB
                    : poolAmountFromA;
    
                bytes32 poolId = bytes32(param.farmingPoolId);
    ->          if (poolAmountOut > 0) {
                    vault.joinPool(
                        poolId,
                        address(this),
                        address(this),
                        IBalancerVault.JoinPoolRequest(
                            tokens,
                            maxAmountsIn,
                            "",
                            false
                        )
                    );
                }
    ```
    
5.  call `_validateMaxLTV`.
    
6.  call `_validateMaxPosSize`.
    
7.  Since alice is a new user, so `pos.collateralSize` is equal to 0. This step will be skipped.
    
8.  `lpAmount = IERC20Upgradeable(lpToken).balanceOf(address(this)) = 10e18`, the 10e18 lptoken was transferred in by bob.
    

Alice has successfully created a position. 50e18 token0 is stuck in the contract. Now, **bob opened a new position, borrowToken is token1**. Because there are token0 and token1 in the contract, `vault.joinPool` is called to get some lptoken. Bob successfully opened his position. After that, he closes the position by `AuraSpell.closePositionFarm`. Attack completed.

## Impact

User suffers loss of funds.

## Code Snippet

https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/spell/AuraSpell.sol#L88-L120

## Tool used

Manual Review

## Recommendation

Spell can only borrow one type of token from the bank, so it is necessary to change the parameters of `IBalancerVault#joinPool` to support a single token to add liquidity. `JoinPoolRequest.userData` should be encoded as following:

- **Single Token Join**
    - userData ABI
        - `['uint256', 'uint256', 'uint256']`
    - userData
        - `[TOKEN_IN_FOR_EXACT_BPT_OUT, bptAmountOut, enterTokenIndex]`

For details, please refer to [[pool-joins](https://docs.balancer.fi/reference/joins-and-exits/pool-joins.html)](https://docs.balancer.fi/reference/joins-and-exits/pool-joins.html).

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is a valid M/H. This issue needs to be brought to the attention of sponsors. From the code of [[openPositionFarm](https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/spell/AuraSpell.sol#L88-L120)](https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/spell/AuraSpell.sol#L88-L120), the developer wants to use token0 and token1 to join the pool. Although the existing vault.joinPool will revert, the attack vectors and suggestions of this report need to be known. The Recommendation from #120 does not prevent this reported attack vector.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> This is a valid M/H. This issue needs to be brought to the attention of sponsors. From the code of [[openPositionFarm](https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/spell/AuraSpell.sol#L88-L120)](https://github.com/sherlock-audit/2023-04-blueberry/blob/main/blueberry-core/contracts/spell/AuraSpell.sol#L88-L120), the developer wants to use token0 and token1 to join the pool. Although the existing vault.joinPool will revert, the attack vectors and suggestions of this report need to be known. The Recommendation from #120 does not prevent this reported attack vector.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
Given that the underlying issue is described incorrectly as there are no tokens left in the contract because joinpool would revert.
Having correct recommendations, although appreciated, is not sufficient to make a submission valid.

Tagging @Gornutz to have a look at the recommendations for this issue as well as #143.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Invalid issue
> Given that the underlying issue is described incorrectly as there are no tokens left in the contract because joinpool would revert.
> Having correct recommendations, although appreciated, is not sufficient to make a submission valid.
> 
> Tagging @Gornutz to have a look at the recommendations for this issue as well as #143. 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
